### ISSUE TITLE
Provide Sample How to do Refresh Token

### ISSUE THREAD

**Issue by edosyhptra** [go-oauth2/oauth2#136]
Currently, Im using client credentials grant flow to implement Oauth2 in Golang.

Now, im trying to refresh the given access token. I have read the documentation. But I still can't figure it out.

if someone can provide me some guidance I would be muchh appreciate it.

**Comment by LyricTian** [comment]
We apologize for the inconvenience caused by the untimely response. You can use the `SetClientTokenCfg` configuration in the `manager`, set the parameter `IsGenerateRefresh` to true, and then refer to the protocol <https://tools.ietf.org/html/rfc6749#section-6>. The client carries a refresh token in exchange for an access token.

**Comment by edosyhptra** [comment]
> We apologize for the inconvenience caused by the untimely response. You can use the `SetClientTokenCfg` configuration in the `manager`, set the parameter `IsGenerateRefresh` to true, and then refer to the protocol https://tools.ietf.org/html/rfc6749#section-6. The client carries a refresh token in exchange for an access token.

Thanks for the reply. appreciate it.
